"""add description to data_sources and data_source_columns

Revision ID: 282a99637c4d
Revises: df2585f09ea6
Create Date: 2026-02-24 21:32:35.533370

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '282a99637c4d'
down_revision: Union[str, Sequence[str], None] = 'df2585f09ea6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('data_source_columns', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('data_sources', sa.Column('description', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('data_sources', 'description')
    op.drop_column('data_source_columns', 'description')
    # ### end Alembic commands ###
