"""add institution_id is_shared description to saved_queries

Revision ID: 2e6a9bda8c33
Revises: 282a99637c4d
Create Date: 2026-02-24 21:42:24.237062

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2e6a9bda8c33'
down_revision: Union[str, Sequence[str], None] = '282a99637c4d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('saved_queries', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('saved_queries', sa.Column('institution_id', sa.UUID(), nullable=True))
    op.add_column('saved_queries', sa.Column('is_shared', sa.Boolean(), nullable=True))
    op.create_foreign_key(None, 'saved_queries', 'institutions', ['institution_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'saved_queries', type_='foreignkey')
    op.drop_column('saved_queries', 'is_shared')
    op.drop_column('saved_queries', 'institution_id')
    op.drop_column('saved_queries', 'description')
    # ### end Alembic commands ###
