"""add is_groupable and group_by aggregations fields

Revision ID: 604001d39dc6
Revises: 2e6a9bda8c33
Create Date: 2026-02-25 17:30:54.206799

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '604001d39dc6'
down_revision: Union[str, Sequence[str], None] = '2e6a9bda8c33'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('role_datasources',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.Column('datasource_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['datasource_id'], ['data_sources.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('role_id', 'datasource_id')
    )
    op.add_column('data_source_columns', sa.Column('is_groupable', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.add_column('saved_queries', sa.Column('group_by', postgresql.JSONB(astext_type=sa.Text()), nullable=False, server_default='[]'))
    op.add_column('saved_queries', sa.Column('aggregations', postgresql.JSONB(astext_type=sa.Text()), nullable=False, server_default='[]'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('saved_queries', 'aggregations')
    op.drop_column('saved_queries', 'group_by')
    op.drop_column('data_source_columns', 'is_groupable')
    op.drop_table('role_datasources')
    # ### end Alembic commands ###
