"""add data_sources data_source_columns saved_queries tables

Revision ID: df2585f09ea6
Revises: 002_seed_data
Create Date: 2026-02-19 07:37:11.008150

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'df2585f09ea6'
down_revision: Union[str, Sequence[str], None] = '002_seed_data'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('data_sources',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('ch_table', sa.String(length=200), nullable=False),
    sa.Column('base_filter', sa.Text(), nullable=True),
    sa.Column('institution_id', sa.UUID(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_data_sources_code'), 'data_sources', ['code'], unique=True)
    op.create_table('data_source_columns',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('datasource_id', sa.UUID(), nullable=False),
    sa.Column('column_name', sa.String(length=100), nullable=False),
    sa.Column('label', sa.String(length=200), nullable=False),
    sa.Column('data_type', sa.Enum('TEXT', 'INTEGER', 'FLOAT', 'BOOLEAN', name='columndatatype'), nullable=False),
    sa.Column('category', sa.Enum('DIMENSION', 'MEASURE', 'INTERVENTION', 'GEO', name='columncategory'), nullable=False),
    sa.Column('is_selectable', sa.Boolean(), nullable=True),
    sa.Column('is_filterable', sa.Boolean(), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['datasource_id'], ['data_sources.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('saved_queries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('datasource_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('selected_columns', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('filters', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['datasource_id'], ['data_sources.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('saved_queries')
    op.drop_table('data_source_columns')
    op.drop_index(op.f('ix_data_sources_code'), table_name='data_sources')
    op.drop_table('data_sources')
    sa.Enum(name='columndatatype').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='columncategory').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
