"""
Configuracion de presets institucionales para la vista /consulta.

Cada institucion tiene:
- table: tabla ClickHouse a consultar
- base_filter: condicion SQL que siempre se aplica (scoping)
- columns: columnas a mostrar en la lista
- detail_columns: columnas adicionales para detalle
- intervention_columns: columnas binarias (0/1) de intervenciones
- allowed_filters: filtros que el usuario puede aplicar
- labels: nombres legibles para las columnas
"""

_COMMON_LABELS = {
    "hogar_id": "ID Hogar",
    "ig3_departamento": "Departamento",
    "ig3_departamento_codigo": "Cod. Depto",
    "ig4_municipio": "Municipio",
    "ig4_municipio_codigo": "Cod. Municipio",
    "ig5_lugar_poblado": "Lugar Poblado",
    "area": "Area",
    "numero_personas": "No. Personas",
    "hombres": "Hombres",
    "mujeres": "Mujeres",
    "ipm_gt": "IPM",
    "ipm_gt_clasificacion": "Clasif. IPM",
}

INSTITUTIONAL_PRESETS = {
    "FODES": {
        "name": "FODES - Fondo de Desarrollo Social",
        "table": "rsh.beneficios_x_hogar",
        "base_filter": "prog_fodes = 1",
        "columns": [
            "hogar_id",
            "ig3_departamento",
            "ig4_municipio",
            "numero_personas",
            "hombres",
            "mujeres",
            "estufa_mejorada",
            "ecofiltro",
            "letrina",
            "repello",
            "piso",
        ],
        "detail_columns": [
            "hogar_id",
            "ig3_departamento",
            "ig3_departamento_codigo",
            "ig4_municipio",
            "ig4_municipio_codigo",
            "ig5_lugar_poblado",
            "area",
            "numero_personas",
            "hombres",
            "mujeres",
            "ipm_gt",
            "ipm_gt_clasificacion",
            "estufa_mejorada",
            "ecofiltro",
            "letrina",
            "repello",
            "piso",
        ],
        "intervention_columns": [
            "estufa_mejorada",
            "ecofiltro",
            "letrina",
            "repello",
            "piso",
        ],
        "allowed_filters": [
            "departamento_codigo",
            "municipio_codigo",
            "buscar",
            "estufa_mejorada",
            "ecofiltro",
            "letrina",
            "repello",
            "piso",
        ],
        "labels": {
            **_COMMON_LABELS,
            "estufa_mejorada": "Estufa Mejorada",
            "ecofiltro": "Ecofiltro",
            "letrina": "Letrina",
            "repello": "Repello",
            "piso": "Piso",
        },
    },
    "MAGA": {
        "name": "MAGA - Ministerio de Agricultura",
        "table": "rsh.beneficios_x_hogar",
        "base_filter": "prog_maga = 1",
        "columns": [
            "hogar_id",
            "ig3_departamento",
            "ig4_municipio",
            "numero_personas",
            "hombres",
            "mujeres",
            "sembro",
            "crio_animal",
        ],
        "detail_columns": [
            "hogar_id",
            "ig3_departamento",
            "ig3_departamento_codigo",
            "ig4_municipio",
            "ig4_municipio_codigo",
            "ig5_lugar_poblado",
            "area",
            "numero_personas",
            "hombres",
            "mujeres",
            "ipm_gt",
            "ipm_gt_clasificacion",
            "sembro",
            "crio_animal",
        ],
        "intervention_columns": [
            "sembro",
            "crio_animal",
        ],
        "allowed_filters": [
            "departamento_codigo",
            "municipio_codigo",
            "buscar",
            "sembro",
            "crio_animal",
        ],
        "labels": {
            **_COMMON_LABELS,
            "sembro": "Sembro",
            "crio_animal": "Crio Animal",
        },
    },
    "MIDES": {
        "name": "MIDES - Ministerio de Desarrollo Social",
        "table": "rsh.beneficios_x_hogar",
        "base_filter": "prog_mides = 1",
        "columns": [
            "hogar_id",
            "ig3_departamento",
            "ig4_municipio",
            "numero_personas",
            "hombres",
            "mujeres",
            "bono_unico",
            "bono_salud",
            "bono_educacion",
            "bolsa_social",
        ],
        "detail_columns": [
            "hogar_id",
            "ig3_departamento",
            "ig3_departamento_codigo",
            "ig4_municipio",
            "ig4_municipio_codigo",
            "ig5_lugar_poblado",
            "area",
            "numero_personas",
            "hombres",
            "mujeres",
            "ipm_gt",
            "ipm_gt_clasificacion",
            "bono_unico",
            "bono_salud",
            "bono_educacion",
            "bolsa_social",
        ],
        "intervention_columns": [
            "bono_unico",
            "bono_salud",
            "bono_educacion",
            "bolsa_social",
        ],
        "allowed_filters": [
            "departamento_codigo",
            "municipio_codigo",
            "buscar",
            "bono_unico",
            "bono_salud",
            "bono_educacion",
            "bolsa_social",
        ],
        "labels": {
            **_COMMON_LABELS,
            "bono_unico": "Bono Unico",
            "bono_salud": "Bono Salud",
            "bono_educacion": "Bono Educacion",
            "bolsa_social": "Bolsa Social",
        },
    },
}
