"""
Configuracion de presets institucionales para la vista /consulta.

Cada institucion tiene:
- table: tabla ClickHouse a consultar
- base_filter: condicion SQL que siempre se aplica (scoping)
- columns: columnas a mostrar en la lista
- detail_columns: columnas adicionales para detalle
- intervention_columns: columnas binarias (0/1) de intervenciones
- allowed_filters: filtros que el usuario puede aplicar
- labels: nombres legibles para las columnas
"""

_COMMON_LABELS = {
    "hogar_id": "ID Hogar",
    "ig3_departamento": "Departamento",
    "ig3_codigo_departamento": "Cod. Depto",
    "ig4_municipio": "Municipio",
    "ig4_codigo_municipio": "Cod. Municipio",
    "ig6_lugar_poblado": "Lugar Poblado",
    "ig8_area": "Area",
    "personas": "No. Personas",
    "hombres": "Hombres",
    "mujeres": "Mujeres",
    "ipm_gt": "IPM",
    "ipm_gt_clasificacion": "Clasif. IPM",
    "pmt": "PMT",
    "pmt_clasificacion": "Clasif. PMT",
    "nbi": "NBI",
    "nbi_clasificacion": "Clasif. NBI",
    "total_intervenciones": "Total Intervenciones",
}

INSTITUTIONAL_PRESETS = {
    "FODES": {
        "name": "FODES - Fondo de Desarrollo Social",
        "table": "rsh.vw_beneficios_x_hogar",
        "base_filter": "prog_fodes = 1",
        "columns": [
            "hogar_id",
            "ig3_departamento",
            "ig4_municipio",
            "personas",
            "hombres",
            "mujeres",
            "estufa_mejorada",
            "ecofiltro",
            "letrina",
            "repello",
            "piso",
        ],
        "detail_columns": [
            "hogar_id",
            "ig3_departamento",
            "ig3_codigo_departamento",
            "ig4_municipio",
            "ig4_codigo_municipio",
            "ig6_lugar_poblado",
            "ig8_area",
            "personas",
            "hombres",
            "mujeres",
            "ipm_gt",
            "ipm_gt_clasificacion",
            "estufa_mejorada",
            "ecofiltro",
            "letrina",
            "repello",
            "piso",
            "total_intervenciones",
        ],
        "intervention_columns": [
            "estufa_mejorada",
            "ecofiltro",
            "letrina",
            "repello",
            "piso",
        ],
        "allowed_filters": [
            "ig3_codigo_departamento",
            "ig4_codigo_municipio",
            "ig3_departamento",
            "ig4_municipio",
            "estufa_mejorada",
            "ecofiltro",
            "letrina",
            "repello",
            "piso",
        ],
        "labels": {
            **_COMMON_LABELS,
            "estufa_mejorada": "Estufa Mejorada",
            "ecofiltro": "Ecofiltro",
            "letrina": "Letrina",
            "repello": "Repello",
            "piso": "Piso",
        },
    },
    "MAGA": {
        "name": "MAGA - Ministerio de Agricultura",
        "table": "rsh.vw_beneficios_x_hogar",
        "base_filter": "prog_maga = 1",
        "columns": [
            "hogar_id",
            "ig3_departamento",
            "ig4_municipio",
            "personas",
            "hombres",
            "mujeres",
            "sembro",
            "crio_animal",
        ],
        "detail_columns": [
            "hogar_id",
            "ig3_departamento",
            "ig3_codigo_departamento",
            "ig4_municipio",
            "ig4_codigo_municipio",
            "ig6_lugar_poblado",
            "ig8_area",
            "personas",
            "hombres",
            "mujeres",
            "ipm_gt",
            "ipm_gt_clasificacion",
            "sembro",
            "crio_animal",
            "total_intervenciones",
        ],
        "intervention_columns": [
            "sembro",
            "crio_animal",
        ],
        "allowed_filters": [
            "ig3_codigo_departamento",
            "ig4_codigo_municipio",
            "ig3_departamento",
            "ig4_municipio",
            "sembro",
            "crio_animal",
        ],
        "labels": {
            **_COMMON_LABELS,
            "sembro": "Sembro",
            "crio_animal": "Crio Animal",
        },
    },
    "MIDES": {
        "name": "MIDES - Ministerio de Desarrollo Social",
        "table": "rsh.vw_beneficios_x_hogar",
        "base_filter": "(prog_bono_social = 1 OR prog_bolsa_social = 1 OR prog_bono_unico = 1)",
        "columns": [
            "hogar_id",
            "ig3_departamento",
            "ig4_municipio",
            "personas",
            "hombres",
            "mujeres",
            "bono_unico",
            "bono_salud",
            "bono_educacion",
            "bolsa_social",
        ],
        "detail_columns": [
            "hogar_id",
            "ig3_departamento",
            "ig3_codigo_departamento",
            "ig4_municipio",
            "ig4_codigo_municipio",
            "ig6_lugar_poblado",
            "ig8_area",
            "personas",
            "hombres",
            "mujeres",
            "ipm_gt",
            "ipm_gt_clasificacion",
            "bono_unico",
            "bono_salud",
            "bono_educacion",
            "bolsa_social",
            "total_intervenciones",
        ],
        "intervention_columns": [
            "bono_unico",
            "bono_salud",
            "bono_educacion",
            "bolsa_social",
        ],
        "allowed_filters": [
            "ig3_codigo_departamento",
            "ig4_codigo_municipio",
            "ig3_departamento",
            "ig4_municipio",
            "bono_unico",
            "bono_salud",
            "bono_educacion",
            "bolsa_social",
        ],
        "labels": {
            **_COMMON_LABELS,
            "bono_unico": "Bono Unico",
            "bono_salud": "Bono Salud",
            "bono_educacion": "Bono Educacion",
            "bolsa_social": "Bolsa Social",
        },
    },
}
