from fastapi import Query
from typing import Optional
from typing_extensions import Annotated

from api.v1.schemas.beneficiario import BeneficiarioFilters


def beneficiario_filters_dep(
    departamento_codigo: Annotated[Optional[str], Query(description="Codigo de departamento")] = None,
    municipio_codigo: Annotated[Optional[str], Query(description="Codigo de municipio")] = None,
    lugar_poblado_codigo: Annotated[Optional[str], Query(description="Codigo de lugar poblado")] = None,
    area: Annotated[Optional[str], Query(description="Area (Urbano/Rural)")] = None,
    sexo_jefe: Annotated[Optional[str], Query(description="Sexo jefe hogar (M/F)")] = None,
    ipm_min: Annotated[Optional[float], Query(description="IPM minimo")] = None,
    ipm_max: Annotated[Optional[float], Query(description="IPM maximo")] = None,
    ipm_clasificacion: Annotated[Optional[str], Query(description="Clasificacion IPM")] = None,
    pmt_clasificacion: Annotated[Optional[str], Query(description="Clasificacion PMT")] = None,
    nbi_clasificacion: Annotated[Optional[str], Query(description="Clasificacion NBI")] = None,
    tiene_menores_5: Annotated[Optional[bool], Query(description="Hogares con menores de 5")] = None,
    tiene_adultos_mayores: Annotated[Optional[bool], Query(description="Hogares con adultos mayores")] = None,
    tiene_embarazadas: Annotated[Optional[bool], Query(description="Hogares con embarazadas")] = None,
    tiene_discapacidad: Annotated[Optional[bool], Query(description="Hogares con discapacidad")] = None,
    nivel_inseguridad: Annotated[Optional[str], Query(description="Nivel inseguridad alimentaria")] = None,
    fuente_agua: Annotated[Optional[str], Query(description="Fuente de agua")] = None,
    tipo_sanitario: Annotated[Optional[str], Query(description="Tipo sanitario")] = None,
    alumbrado: Annotated[Optional[str], Query(description="Tipo alumbrado")] = None,
    combustible_cocina: Annotated[Optional[str], Query(description="Combustible cocina")] = None,
    tiene_internet: Annotated[Optional[bool], Query(description="Hogar con internet")] = None,
    tiene_computadora: Annotated[Optional[bool], Query(description="Hogar con computadora")] = None,
    tiene_refrigerador: Annotated[Optional[bool], Query(description="Hogar con refrigerador")] = None,
    con_hacinamiento: Annotated[Optional[bool], Query(description="Hogar con hacinamiento")] = None,
    con_analfabetismo: Annotated[Optional[bool], Query(description="Hogar con persona que no sabe leer/escribir")] = None,
    con_menores_sin_escuela: Annotated[Optional[bool], Query(description="Hogar con menores no inscritos en escuela")] = None,
    sin_empleo: Annotated[Optional[bool], Query(description="Hogar sin personas con empleo")] = None,
    buscar: Annotated[Optional[str], Query(description="Buscar por nombre o CUI")] = None,
    anio: Annotated[Optional[int], Query(description="Anio de captura")] = None,
    fase: Annotated[Optional[str], Query(description="Fase de intervencion")] = None,
) -> BeneficiarioFilters:
    return BeneficiarioFilters(
        departamento_codigo=departamento_codigo,
        municipio_codigo=municipio_codigo,
        lugar_poblado_codigo=lugar_poblado_codigo,
        area=area,
        sexo_jefe=sexo_jefe,
        ipm_min=ipm_min,
        ipm_max=ipm_max,
        ipm_clasificacion=ipm_clasificacion,
        pmt_clasificacion=pmt_clasificacion,
        nbi_clasificacion=nbi_clasificacion,
        tiene_menores_5=tiene_menores_5,
        tiene_adultos_mayores=tiene_adultos_mayores,
        tiene_embarazadas=tiene_embarazadas,
        tiene_discapacidad=tiene_discapacidad,
        nivel_inseguridad=nivel_inseguridad,
        fuente_agua=fuente_agua,
        tipo_sanitario=tipo_sanitario,
        alumbrado=alumbrado,
        combustible_cocina=combustible_cocina,
        tiene_internet=tiene_internet,
        tiene_computadora=tiene_computadora,
        tiene_refrigerador=tiene_refrigerador,
        con_hacinamiento=con_hacinamiento,
        con_analfabetismo=con_analfabetismo,
        con_menores_sin_escuela=con_menores_sin_escuela,
        sin_empleo=sin_empleo,
        buscar=buscar,
        anio=anio,
        fase=fase,
    )
